
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace InterviewEvaluation.EntityModels
{

using System;
    using System.Collections.Generic;
    
public partial class AspNetUser
{

    public int Id { get; set; }

    public string Email { get; set; }

    public string PasswordHash { get; set; }

    public int AccessFailedCount { get; set; }

    public string BioText { get; set; }

    public string FullName { get; set; }

    public string ImgName { get; set; }

    public byte[] ImgData { get; set; }



    public virtual AspNetRole AspNetRoles { get; set; }

}

}
